version: '3.3'

networks:
  backend:
    driver: bridge
  proxy:
    external: true

services:

  site:
    build:
      context: ./site
      args:
        - NODE_VERSION=latest
        - PROJECT_PATH=/opt/app/
        - NODE_ENV=production
        - YARN=true
    env_file:
      - .env
    volumes:
      - ../site:/opt/app
    entrypoint: run "yarn run build && yarn run start"
    tty: true
    restart: always
    networks:
      - backend

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../data/logs/nginx/:/var/log/nginx
      - ./nginx/sites/:/etc/nginx/sites-available
    depends_on:
      - site
    tty: true
    restart: always
    networks:
      - proxy
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myidealtent.rule=Host(`myidealtent.com`)"
      - "traefik.http.routers.myidealtent.entrypoints=websecure"
      - "traefik.http.routers.myidealtent.tls.certresolver=mytlschallenge"